app_name            = "app-name"
aws_region          = "sa-east-1"
base_url            = "testaws.jvictorv.top"
lambda_bucket_name  = "app-name-lambda-bucket"
lambda_gateway_name = "app-name-lambda-gateway"
